# Generated by Django 4.2.6 on 2024-02-08 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wms', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='WMS (in lakhs)')),
                ('wps', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='WPS (in lakhs)')),
                ('pwds', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='PWDS (in lakhs)')),
                ('hrdpa', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='HRDPA (in lakhs)')),
                ('admin_exp', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Admin Exp (in lakhs)')),
                ('financial_year', models.CharField(choices=[('2000-2001', '2000-2001'), ('2001-2002', '2001-2002'), ('2002-2003', '2002-2003'), ('2003-2004', '2003-2004'), ('2004-2005', '2004-2005'), ('2005-2006', '2005-2006'), ('2006-2007', '2006-2007'), ('2007-2008', '2007-2008'), ('2008-2009', '2008-2009'), ('2009-2010', '2009-2010'), ('2010-2011', '2010-2011'), ('2011-2012', '2011-2012'), ('2012-2013', '2012-2013'), ('2013-2014', '2013-2014'), ('2014-2015', '2014-2015'), ('2015-2016', '2015-2016'), ('2016-2017', '2016-2017'), ('2017-2018', '2017-2018'), ('2018-2019', '2018-2019'), ('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_address', models.TextField()),
                ('implementingAgencyState', models.CharField(blank=True, max_length=100, null=True)),
                ('project_scheme', models.CharField(max_length=20)),
                ('scheme_component', models.CharField(max_length=100)),
                ('nature_of_applicant', models.CharField(max_length=50)),
                ('other_nature', models.CharField(blank=True, max_length=50, null=True)),
                ('brief_of_agency', models.TextField()),
                ('objectives_of_project', models.TextField()),
                ('brief_of_project', models.TextField()),
                ('justification_of_project', models.TextField()),
                ('methodology_of_project', models.TextField()),
                ('expected_outcome', models.FileField(blank=True, null=True, upload_to='expected_outcomes/')),
                ('scenario_change', models.TextField()),
                ('beneficiaries', models.FileField(blank=True, null=True, upload_to='beneficiaries/')),
                ('mode_of_selection', models.TextField()),
                ('component_wise_cost', models.FileField(blank=True, null=True, upload_to='project_costs/')),
                ('component_wise_duration', models.FileField(blank=True, null=True, upload_to='durations/')),
                ('location_of_project', models.CharField(max_length=100)),
                ('associated_agency', models.TextField()),
                ('bank_details', models.TextField()),
                ('nodal_officer_details', models.TextField()),
                ('other_info', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Resubmit', 'Resubmit')], default='Pending', max_length=20)),
                ('total_fund_allocated', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('project_sanction_letter', models.FileField(null=True, upload_to='sanction_letters/')),
                ('Approved_by', models.CharField(blank=True, max_length=50, null=True)),
                ('project_report', models.FileField(blank=True, null=True, upload_to='project_reports/')),
                ('covering_letter', models.FileField(blank=True, null=True, upload_to='covering_letters/')),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('total_duration', models.IntegerField(blank=True, null=True)),
                ('goals', models.JSONField(default=dict)),
                ('reminder_financial_year', models.CharField(blank=True, choices=[('2000-2001', '2000-2001'), ('2001-2002', '2001-2002'), ('2002-2003', '2002-2003'), ('2003-2004', '2003-2004'), ('2004-2005', '2004-2005'), ('2005-2006', '2005-2006'), ('2006-2007', '2006-2007'), ('2007-2008', '2007-2008'), ('2008-2009', '2008-2009'), ('2009-2010', '2009-2010'), ('2010-2011', '2010-2011'), ('2011-2012', '2011-2012'), ('2012-2013', '2012-2013'), ('2013-2014', '2013-2014'), ('2014-2015', '2014-2015'), ('2015-2016', '2015-2016'), ('2016-2017', '2016-2017'), ('2017-2018', '2017-2018'), ('2018-2019', '2018-2019'), ('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], max_length=10, null=True)),
                ('reminder_quarter', models.CharField(blank=True, choices=[('Q1', 'Quarter 1 (April-June)'), ('Q2', 'Quarter 2 (July-September)'), ('Q3', 'Quarter 3 (October-December)'), ('Q4', 'Quarter 4 (January-March)')], max_length=5, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SanctionLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_sanctioned', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sanction_letter', models.FileField(upload_to='sanction_letters/')),
                ('installment_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cwdb_admin.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_letter', models.FileField(upload_to='inspection_letters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cwdb_admin.proposal')),
            ],
        ),
    ]
