# Generated by Django 4.2.6 on 2024-02-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwdb_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sanctionletter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
