# Generated by Django 4.2.6 on 2024-02-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwdb_admin', '0002_inspectionreport_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='expected_outcome',
            field=models.TextField(null=True),
        ),
    ]
