# Generated by Django 4.2.6 on 2024-02-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwdb_admin', '0004_index_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
