# Generated by Django 4.2.6 on 2024-02-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwdb_admin', '0005_alter_proposal_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
    ]
