# Generated by Django 4.2.6 on 2024-02-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwdb_admin', '0006_proposal_approved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='location_of_project',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='reminder_quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'Quarter 1 (April-June)'), ('Q2', 'Quarter 2 (July-September)'), ('Q3', 'Quarter 3 (October-December)'), ('Q4', 'Quarter 4 (January-March)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='total_fund_allocated',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
