# Generated by Django 4.2.6 on 2024-02-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwdb_admin', '0008_admin_exp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin_exp',
            new_name='Administrative_Expenditure',
        ),
    ]
