# Generated by Django 4.2.6 on 2024-02-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwdb_admin', '0009_rename_admin_exp_administrative_expenditure'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrative_Expenditure',
            new_name='AdministrativeExpenditure',
        ),
    ]
