# Generated by Django 4.2.6 on 2024-03-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwdb_admin', '0010_rename_administrative_expenditure_administrativeexpenditure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='nature_of_applicant',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='other_nature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
