# Generated by Django 4.2.6 on 2024-03-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwdb_admin', '0011_alter_proposal_nature_of_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='nature_of_applicant',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='other_nature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
