# Generated by Django 4.2.6 on 2024-04-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwdb_admin', '0012_alter_proposal_nature_of_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='scheme_component',
            field=models.CharField(max_length=200),
        ),
    ]
