# Generated by Django 4.2.6 on 2023-11-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_customuser_agency_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='fund_allocated',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='sanction_letter',
            field=models.FileField(blank=True, null=True, upload_to='sanction_letters/'),
        ),
    ]
