# Generated by Django 4.2.6 on 2023-11-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_proposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='scheme_component',
            field=models.CharField(max_length=100),
        ),
    ]
