# Generated by Django 4.2.6 on 2023-11-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_proposal_scheme_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='fund_allocated',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
