# Generated by Django 4.2.6 on 2023-11-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='attachment_content',
            field=models.FileField(blank=True, null=True, upload_to='notification_attachments/'),
        ),
    ]
