# Generated by Django 4.2.6 on 2023-11-13 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_notification_attachment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='attachment_content',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='attachment_name',
        ),
    ]
