# Generated by Django 4.2.6 on 2023-11-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_notification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Resubmit', 'Resubmit')], default='Pending', max_length=20),
        ),
    ]
