# Generated by Django 4.2.6 on 2023-11-20 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_alter_proposal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'Quarter 1 (April-June)'), ('Q2', 'Quarter 2 (July-September)'), ('Q3', 'Quarter 3 (October-December)'), ('Q4', 'Quarter 4 (January-March)')], max_length=10)),
                ('financial_year', models.CharField(max_length=9)),
                ('document', models.FileField(upload_to='progress_report_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal_unique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.proposal', to_field='unique_id')),
            ],
        ),
    ]
