# Generated by Django 4.2.6 on 2023-11-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_progressreportdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='covering_letter',
            field=models.FileField(blank=True, null=True, upload_to='pdf_files/'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='project_report',
            field=models.FileField(blank=True, null=True, upload_to='pdf_files/'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='beneficiaries',
            field=models.FileField(blank=True, null=True, upload_to='excel_files/'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='component_wise_cost',
            field=models.FileField(blank=True, null=True, upload_to='excel_files/'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='expected_outcome',
            field=models.FileField(blank=True, null=True, upload_to='excel_files/'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='total_duration',
            field=models.FileField(blank=True, null=True, upload_to='excel_files/'),
        ),
    ]
