# Generated by Django 4.2.6 on 2023-12-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_proposal_covering_letter_proposal_project_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='agency_nature',
            field=models.CharField(choices=[('Central Federations', 'Central Federations'), ('State Federations', 'State Federations'), ('Central Sheep & Wool Boards', 'Central Sheep & Wool Boards'), ('State Sheep & Wool Boards', 'State Sheep & Wool Boards'), ('UT Govt. Sheep & Wool Boards', 'UT Govt. Sheep & Wool Boards'), ('UT Govt. Sheep & Wool Federations', 'UT Govt. Sheep & Wool Federations'), ('State Govt. Corporations Federations', 'State Govt. Corporations Federations'), ('Central Departments', 'Central Departments'), ('State Departments', 'State Departments'), ('UT Statutory Departments', 'UT Statutory Departments'), ('Autonomous and Advisory Bodies Departments', 'Autonomous and Advisory Bodies Departments'), ('State Cooperative Departments', 'State Cooperative Departments'), ('UT Cooperative Departments', 'UT Cooperative Departments'), ('Central Govt Cooperative Departments', 'Central Govt Cooperative Departments'), ('Central Govt Animal Husbandry Department', 'Central Govt Animal Husbandry Department'), ('State Govt. Animal Husbandry Department', 'State Govt. Animal Husbandry Department'), ('UT Animal Husbandry Department', 'UT Animal Husbandry Department'), ('State Industries Department', 'State Industries Department'), ('Central Industries Department', 'Central Industries Department'), ('UT Industries Department', 'UT Industries Department'), ('Central Organizations', 'Central Organizations'), ('State Organizations', 'State Organizations'), ('UT Government Organizations', 'UT Government Organizations'), ('Universities of State', 'Universities of State'), ('Universities of Central Govt', 'Universities of Central Govt'), ('Universities of UT', 'Universities of UT'), ('Govt. marketing event organizers', 'Govt. marketing event organizers'), ('Central Research & Development Institutions', 'Central Research & Development Institutions'), ('State Research & Development Institutions', 'State Research & Development Institutions'), ('UT Govts. Autonomous Research & Development Institutions', 'UT Govts. Autonomous Research & Development Institutions'), ('Statutory Bodies Research & Development Institutions', 'Statutory Bodies Research & Development Institutions'), ('Textiles Research Associations (TRAs)', 'Textiles Research Associations (TRAs)')], default='Central Federations', max_length=56),
        ),
    ]
