# Generated by Django 4.2.6 on 2023-12-21 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_alter_customuser_agency_nature'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_beneficiaries', models.PositiveIntegerField()),
                ('num_general_beneficiaries', models.PositiveIntegerField()),
                ('num_obc_beneficiaries', models.PositiveIntegerField()),
                ('num_sc_st_beneficiaries', models.PositiveIntegerField()),
                ('state_of_beneficiaries', models.CharField(max_length=100)),
                ('num_males', models.PositiveIntegerField()),
                ('num_females', models.PositiveIntegerField()),
                ('num_other_gender', models.PositiveIntegerField()),
                ('quarter', models.CharField(choices=[('Q1', 'Quarter 1 (April-June)'), ('Q2', 'Quarter 2 (July-September)'), ('Q3', 'Quarter 3 (October-December)'), ('Q4', 'Quarter 4 (January-March)')], max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('scheme', models.CharField(max_length=100)),
                ('proposal_unique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.proposal', to_field='unique_id')),
            ],
        ),
    ]
