# Generated by Django 4.2.6 on 2023-12-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_remove_beneficiarydata_num_sc_st_beneficiaries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiarydata',
            name='state_of_beneficiaries',
            field=models.CharField(max_length=100),
        ),
    ]
