# Generated by Django 4.2.6 on 2023-12-25 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_alter_beneficiarydata_state_of_beneficiaries'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenditureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarterly_budget_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quarterly_budget_allocated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quarter', models.CharField(choices=[('Q1', 'Quarter 1 (April-June)'), ('Q2', 'Quarter 2 (July-September)'), ('Q3', 'Quarter 3 (October-December)'), ('Q4', 'Quarter 4 (January-March)')], max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('scheme', models.CharField(max_length=100)),
                ('proposal_unique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.proposal', to_field='unique_id')),
            ],
        ),
    ]
