# Generated by Django 4.2.6 on 2023-12-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0018_expendituredata'),
    ]

    operations = [
        migrations.AddField(
            model_name='eportal',
            name='quarterly_allocated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wms_selfhelpgroup',
            name='quarterly_allocated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
