# Generated by Django 4.2.6 on 2023-12-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0020_alter_customuser_agency_nature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IWDP', models.BigIntegerField()),
                ('WMS', models.BigIntegerField()),
                ('WPS', models.BigIntegerField()),
                ('PWDS', models.BigIntegerField()),
                ('HRDPA', models.BigIntegerField()),
                ('Admin_exp', models.BigIntegerField()),
                ('financial_year', models.CharField(max_length=9)),
            ],
        ),
    ]
