# Generated by Django 4.2.6 on 2023-12-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0021_funddistribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funddistribution',
            name='Admin_exp',
        ),
        migrations.RemoveField(
            model_name='funddistribution',
            name='HRDPA',
        ),
        migrations.RemoveField(
            model_name='funddistribution',
            name='IWDP',
        ),
        migrations.RemoveField(
            model_name='funddistribution',
            name='PWDS',
        ),
        migrations.RemoveField(
            model_name='funddistribution',
            name='WMS',
        ),
        migrations.RemoveField(
            model_name='funddistribution',
            name='WPS',
        ),
        migrations.AddField(
            model_name='funddistribution',
            name='admin_exp',
            field=models.BigIntegerField(default=0, verbose_name='Admin Exp (in lakhs)'),
        ),
        migrations.AddField(
            model_name='funddistribution',
            name='hrdpa',
            field=models.BigIntegerField(default=0, verbose_name='HRDPA (in lakhs)'),
        ),
        migrations.AddField(
            model_name='funddistribution',
            name='pwds',
            field=models.BigIntegerField(default=0, verbose_name='PWDS (in lakhs)'),
        ),
        migrations.AddField(
            model_name='funddistribution',
            name='wms',
            field=models.BigIntegerField(default=0, verbose_name='WMS (in lakhs)'),
        ),
        migrations.AddField(
            model_name='funddistribution',
            name='wps',
            field=models.BigIntegerField(default=0, verbose_name='WPS (in lakhs)'),
        ),
    ]
