# Generated by Django 4.2.6 on 2023-12-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0022_remove_funddistribution_admin_exp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funddistribution',
            name='admin_exp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Admin Exp (in lakhs)'),
        ),
        migrations.AlterField(
            model_name='funddistribution',
            name='hrdpa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='HRDPA (in lakhs)'),
        ),
        migrations.AlterField(
            model_name='funddistribution',
            name='pwds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='PWDS (in lakhs)'),
        ),
        migrations.AlterField(
            model_name='funddistribution',
            name='wms',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='WMS (in lakhs)'),
        ),
        migrations.AlterField(
            model_name='funddistribution',
            name='wps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='WPS (in lakhs)'),
        ),
    ]
