# Generated by Django 4.2.6 on 2024-01-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0025_alter_funddistribution_financial_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiarydata',
            name='num_beneficiaries',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
