# Generated by Django 4.2.6 on 2024-01-18 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0026_alter_beneficiarydata_num_beneficiaries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wooltestinglab',
            old_name='training_details_wtc_sheet',
            new_name='training_details_wdtc_sheet',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='fund_allocated',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='sanction_letter',
        ),
        migrations.RemoveField(
            model_name='wms_buyersellerexpo',
            name='wool_sold_sheet',
        ),
        migrations.CreateModel(
            name='SanctionLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_sanctioned', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sanction_letter', models.FileField(upload_to='sanction_letters/')),
                ('installment_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.proposal')),
            ],
        ),
    ]
