# Generated by Django 4.2.6 on 2024-01-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0028_rename_master_trainer_details_sheet_domesticmeeting_participants_details_sheet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='sanction_letter',
            new_name='project_sanction_letter',
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='fund_allocated',
            new_name='total_fund_allocated',
        ),
    ]
