# Generated by Django 4.2.6 on 2024-01-18 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0029_rename_sanction_letter_proposal_project_sanction_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='Approved_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SanctionLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_sanctioned', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sanction_letter', models.FileField(upload_to='sanction_letters/')),
                ('installment_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.proposal')),
            ],
        ),
    ]
