# Generated by Django 4.2.6 on 2024-01-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0030_proposal_approved_by_sanctionletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='Approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
