# Generated by Django 4.2.6 on 2024-01-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0032_rename_total_duration_proposal_component_wise_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='goals',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='proposal',
            name='total_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
