# Generated by Django 4.2.6 on 2024-01-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0034_inspectionreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiarydata',
            name='year',
            field=models.CharField(max_length=9),
        ),
    ]
