# Generated by Django 4.2.6 on 2024-01-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0036_alter_beneficiarydata_state_of_beneficiaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='implementingAgencyState',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expendituredata',
            name='year',
            field=models.CharField(max_length=9),
        ),
    ]
