# Generated by Django 4.2.6 on 2024-01-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0037_proposal_implementingagencystate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SummReportGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('q1', 'Q1'), ('q2', 'Q2'), ('q3', 'Q3'), ('q4', 'Q4')], max_length=2)),
                ('financial_year', models.CharField(max_length=9)),
                ('project_name', models.CharField(max_length=100)),
                ('subcomponent', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ManyToManyField(choices=[('HRD', 'HRD'), ('WPS', 'WPS'), ('WMS', 'WMS'), ('PWDS', 'PWDS')], to='authapp.scheme')),
            ],
        ),
    ]
