# Generated by Django 4.2.6 on 2024-01-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0038_scheme_summreportgen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expendituredata',
            name='scheme',
            field=models.CharField(choices=[('WMS', 'WMS'), ('WPS', 'WPS'), ('HRD', 'HRD'), ('PWDS', 'PWDS')], max_length=10),
        ),
    ]
