# Generated by Django 4.2.6 on 2024-01-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0039_alter_expendituredata_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='beneficiaries',
            field=models.FileField(blank=True, null=True, upload_to='beneficiaries/'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='component_wise_cost',
            field=models.FileField(blank=True, null=True, upload_to='project_costs/'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='component_wise_duration',
            field=models.FileField(blank=True, null=True, upload_to='durations/'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='covering_letter',
            field=models.FileField(blank=True, null=True, upload_to='covering_letters/'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='expected_outcome',
            field=models.FileField(blank=True, null=True, upload_to='expected_outcomes/'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='project_report',
            field=models.FileField(blank=True, null=True, upload_to='project_reports/'),
        ),
    ]
