# Generated by Django 4.2.6 on 2024-02-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0041_alter_proposal_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='unique_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
