# Generated by Django 4.2.6 on 2024-02-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0039_alter_summreportgen_quarter'),
        ('authapp', '0042_alter_proposal_unique_id'),
    ]

    operations = [
    ]
