# Generated by Django 4.2.6 on 2024-02-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0043_merge_20240202_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summreportgen',
            name='quarter',
            field=models.CharField(choices=[('q1', 'Q1'), ('q2', 'Q2'), ('q3', 'Q3'), ('q4', 'Q4')], max_length=2),
        ),
    ]
