# Generated by Django 4.2.6 on 2024-02-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0044_alter_summreportgen_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='reminder_financial_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='reminder_quarter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
