# Generated by Django 4.2.6 on 2024-02-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0046_alter_proposal_reminder_financial_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='reminder_financial_year',
        ),
    ]
