# Generated by Django 4.2.6 on 2024-02-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0048_remove_proposal_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
