# Generated by Django 4.2.6 on 2024-02-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0049_proposal_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='agency_name',
            field=models.TextField(default='', max_length=100),
        ),
    ]
