# Generated by Django 4.2.6 on 2024-02-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0052_alter_customuser_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='updated_at',
        ),
    ]
