# Generated by Django 4.2.6 on 2024-02-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0053_remove_proposal_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
