# Generated by Django 4.2.6 on 2024-02-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0054_proposal_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
