# Generated by Django 4.2.6 on 2024-02-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0059_beneficiarydata_updated_at_customuser_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='woolenexpo',
            old_name='allocated_budget',
            new_name='quarterly_allocated_budget',
        ),
        migrations.RenameField(
            model_name='woolenexpohiring',
            old_name='allocated_budget',
            new_name='quarterly_allocated_budget',
        ),
    ]
