# Generated by Django 4.2.6 on 2024-02-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0060_rename_allocated_budget_woolenexpo_quarterly_allocated_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='woolsurvey',
            name='survey_outcome',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='woolsurvey',
            name='survey_location',
            field=models.CharField(max_length=100),
        ),
    ]
