# Generated by Django 4.2.6 on 2024-03-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0061_woolsurvey_survey_outcome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rd',
            name='name_project',
            field=models.CharField(max_length=100),
        ),
    ]
